"""base_revision

Revision ID: 08f51db8dce0
Revises: 
Create Date: 2025-11-15 17:53:47.410136

NOTES:
- This base revision represents the complete schema state after all manual SQL migrations
  (g16_webhook_enrichment.sql, g17_notes_tags_favorites.sql, g18_rescan_alerts_scoring.sql,
   g19_favorites_migration.sql, g19_users_auth.sql, g20_domain_intelligence.sql)
- The original SQL migration files have been moved to app/db/migrations/legacy/ for reference
- This revision was created via autogenerate from the current production schema
- All future schema changes will be managed through Alembic revisions

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08f51db8dce0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_config', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('alert_config', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('alert_config', 'frequency',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'immediate'::character varying"))
    op.alter_column('alert_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('alert_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('alert_config_user_id_alert_type_notification_method_key', 'alert_config', type_='unique')
    op.drop_index('idx_alert_config_alert_type', table_name='alert_config')
    op.drop_index('idx_alert_config_enabled', table_name='alert_config')
    op.drop_index('idx_alert_config_user_id', table_name='alert_config')
    op.create_index(op.f('ix_alert_config_alert_type'), 'alert_config', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_config_enabled'), 'alert_config', ['enabled'], unique=False)
    op.create_index(op.f('ix_alert_config_id'), 'alert_config', ['id'], unique=False)
    op.create_index(op.f('ix_alert_config_user_id'), 'alert_config', ['user_id'], unique=False)
    op.drop_table_comment(
        'alert_config',
        existing_comment='Alert configuration preferences (G18)',
        schema=None
    )
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_alerts_alert_type', table_name='alerts')
    op.drop_index('idx_alerts_created_at', table_name='alerts')
    op.drop_index('idx_alerts_domain', table_name='alerts')
    op.drop_index('idx_alerts_status', table_name='alerts')
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_domain'), 'alerts', ['domain'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.drop_table_comment(
        'alerts',
        existing_comment='Generated alerts for domain changes (G18)',
        schema=None
    )
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('companies_domain_key', 'companies', type_='unique')
    op.drop_index('idx_companies_domain', table_name='companies')
    op.drop_index('idx_companies_provider', table_name='companies')
    op.drop_index('idx_companies_tenant_size', table_name='companies')
    op.drop_index('idx_companies_updated_at', table_name='companies')
    op.create_index(op.f('ix_companies_contact_quality_score'), 'companies', ['contact_quality_score'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_provider'), 'companies', ['provider'], unique=False)
    op.create_index(op.f('ix_companies_tenant_size'), 'companies', ['tenant_size'], unique=False)
    op.create_index(op.f('ix_companies_updated_at'), 'companies', ['updated_at'], unique=False)
    op.drop_table_comment(
        'companies',
        existing_comment='Normalized company information with unique domain constraint',
        schema=None
    )
    op.alter_column('domain_signals', 'scan_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('domain_signals', 'scanned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_domain_signals_dmarc_coverage', table_name='domain_signals')
    op.drop_index('idx_domain_signals_domain', table_name='domain_signals')
    op.drop_index('idx_domain_signals_local_provider', table_name='domain_signals')
    op.drop_index('idx_domain_signals_mx_root', table_name='domain_signals')
    op.drop_index('idx_domain_signals_scan_status', table_name='domain_signals')
    op.drop_index('idx_domain_signals_scanned_at', table_name='domain_signals')
    op.create_index(op.f('ix_domain_signals_dmarc_coverage'), 'domain_signals', ['dmarc_coverage'], unique=False)
    op.create_index(op.f('ix_domain_signals_domain'), 'domain_signals', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_signals_id'), 'domain_signals', ['id'], unique=False)
    op.create_index(op.f('ix_domain_signals_local_provider'), 'domain_signals', ['local_provider'], unique=False)
    op.create_index(op.f('ix_domain_signals_mx_root'), 'domain_signals', ['mx_root'], unique=False)
    op.create_index(op.f('ix_domain_signals_scan_status'), 'domain_signals', ['scan_status'], unique=False)
    op.create_index(op.f('ix_domain_signals_scanned_at'), 'domain_signals', ['scanned_at'], unique=False)
    op.drop_table_comment(
        'domain_signals',
        existing_comment='DNS and WHOIS analysis results for domains',
        schema=None
    )
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_favorites_domain', table_name='favorites')
    op.drop_index('idx_favorites_domain_user_id', table_name='favorites')
    op.drop_index('idx_favorites_user_id', table_name='favorites')
    op.drop_index('idx_favorites_user_id_new', table_name='favorites')
    op.create_index(op.f('ix_favorites_domain'), 'favorites', ['domain'], unique=False)
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.drop_table_comment(
        'favorites',
        existing_comment='User favorites for domains, session-based (G17: CRM-lite)',
        schema=None
    )
    op.drop_column('favorites', 'user_id_new')
    op.alter_column('lead_scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_lead_scores_domain', table_name='lead_scores')
    op.drop_index('idx_lead_scores_readiness_score', table_name='lead_scores')
    op.drop_index('idx_lead_scores_segment', table_name='lead_scores')
    op.drop_index('idx_lead_scores_updated_at', table_name='lead_scores')
    op.create_index(op.f('ix_lead_scores_domain'), 'lead_scores', ['domain'], unique=False)
    op.create_index(op.f('ix_lead_scores_id'), 'lead_scores', ['id'], unique=False)
    op.create_index(op.f('ix_lead_scores_readiness_score'), 'lead_scores', ['readiness_score'], unique=False)
    op.create_index(op.f('ix_lead_scores_segment'), 'lead_scores', ['segment'], unique=False)
    op.create_index(op.f('ix_lead_scores_updated_at'), 'lead_scores', ['updated_at'], unique=False)
    op.drop_table_comment(
        'lead_scores',
        existing_comment='Calculated readiness scores and segments for domains',
        schema=None
    )
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_notes_created_at', table_name='notes')
    op.drop_index('idx_notes_domain', table_name='notes')
    op.create_index(op.f('ix_notes_created_at'), 'notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_notes_domain'), 'notes', ['domain'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.drop_table_comment(
        'notes',
        existing_comment='User notes for domains (G17: CRM-lite)',
        schema=None
    )
    op.alter_column('raw_leads', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_raw_leads_domain', table_name='raw_leads')
    op.drop_index('idx_raw_leads_ingested_at', table_name='raw_leads')
    op.drop_index('idx_raw_leads_source', table_name='raw_leads')
    op.create_index(op.f('ix_raw_leads_domain'), 'raw_leads', ['domain'], unique=False)
    op.create_index(op.f('ix_raw_leads_id'), 'raw_leads', ['id'], unique=False)
    op.create_index(op.f('ix_raw_leads_source'), 'raw_leads', ['source'], unique=False)
    op.drop_table_comment(
        'raw_leads',
        existing_comment='Raw ingested data from various sources',
        schema=None
    )
    op.alter_column('score_change_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_score_change_history_changed_at', table_name='score_change_history')
    op.drop_index('idx_score_change_history_domain', table_name='score_change_history')
    op.create_index(op.f('ix_score_change_history_changed_at'), 'score_change_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_score_change_history_domain'), 'score_change_history', ['domain'], unique=False)
    op.create_index(op.f('ix_score_change_history_id'), 'score_change_history', ['id'], unique=False)
    op.drop_table_comment(
        'score_change_history',
        existing_comment='History of score and segment changes (G18)',
        schema=None
    )
    op.alter_column('signal_change_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_signal_change_history_changed_at', table_name='signal_change_history')
    op.drop_index('idx_signal_change_history_domain', table_name='signal_change_history')
    op.drop_index('idx_signal_change_history_signal_type', table_name='signal_change_history')
    op.create_index(op.f('ix_signal_change_history_changed_at'), 'signal_change_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_signal_change_history_domain'), 'signal_change_history', ['domain'], unique=False)
    op.create_index(op.f('ix_signal_change_history_id'), 'signal_change_history', ['id'], unique=False)
    op.create_index(op.f('ix_signal_change_history_signal_type'), 'signal_change_history', ['signal_type'], unique=False)
    op.drop_table_comment(
        'signal_change_history',
        existing_comment='History of signal changes (SPF, DKIM, DMARC, MX) (G18)',
        schema=None
    )
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_tags_domain', table_name='tags')
    op.drop_index('idx_tags_domain_tag', table_name='tags')
    op.drop_index('idx_tags_tag', table_name='tags')
    op.drop_constraint('tags_domain_tag_key', 'tags', type_='unique')
    op.create_index(op.f('ix_tags_domain'), 'tags', ['domain'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.drop_table_comment(
        'tags',
        existing_comment='Tags for domains with auto-tagging support (G17: CRM-lite)',
        schema=None
    )
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_last_login_at', table_name='users')
    op.drop_index('idx_users_microsoft_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_microsoft_id', 'users', ['microsoft_id'], unique=False)
    op.create_index('idx_users_last_login_at', 'users', ['last_login_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table_comment(
        'tags',
        'Tags for domains with auto-tagging support (G17: CRM-lite)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_domain'), table_name='tags')
    op.create_unique_constraint('tags_domain_tag_key', 'tags', ['domain', 'tag'])
    op.create_index('idx_tags_tag', 'tags', ['tag'], unique=False)
    op.create_index('idx_tags_domain_tag', 'tags', ['domain', 'tag'], unique=False)
    op.create_index('idx_tags_domain', 'tags', ['domain'], unique=False)
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'signal_change_history',
        'History of signal changes (SPF, DKIM, DMARC, MX) (G18)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_signal_change_history_signal_type'), table_name='signal_change_history')
    op.drop_index(op.f('ix_signal_change_history_id'), table_name='signal_change_history')
    op.drop_index(op.f('ix_signal_change_history_domain'), table_name='signal_change_history')
    op.drop_index(op.f('ix_signal_change_history_changed_at'), table_name='signal_change_history')
    op.create_index('idx_signal_change_history_signal_type', 'signal_change_history', ['signal_type'], unique=False)
    op.create_index('idx_signal_change_history_domain', 'signal_change_history', ['domain'], unique=False)
    op.create_index('idx_signal_change_history_changed_at', 'signal_change_history', ['changed_at'], unique=False)
    op.alter_column('signal_change_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'score_change_history',
        'History of score and segment changes (G18)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_score_change_history_id'), table_name='score_change_history')
    op.drop_index(op.f('ix_score_change_history_domain'), table_name='score_change_history')
    op.drop_index(op.f('ix_score_change_history_changed_at'), table_name='score_change_history')
    op.create_index('idx_score_change_history_domain', 'score_change_history', ['domain'], unique=False)
    op.create_index('idx_score_change_history_changed_at', 'score_change_history', ['changed_at'], unique=False)
    op.alter_column('score_change_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'raw_leads',
        'Raw ingested data from various sources',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_raw_leads_source'), table_name='raw_leads')
    op.drop_index(op.f('ix_raw_leads_id'), table_name='raw_leads')
    op.drop_index(op.f('ix_raw_leads_domain'), table_name='raw_leads')
    op.create_index('idx_raw_leads_source', 'raw_leads', ['source'], unique=False)
    op.create_index('idx_raw_leads_ingested_at', 'raw_leads', ['ingested_at'], unique=False)
    op.create_index('idx_raw_leads_domain', 'raw_leads', ['domain'], unique=False)
    op.alter_column('raw_leads', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'notes',
        'User notes for domains (G17: CRM-lite)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_domain'), table_name='notes')
    op.drop_index(op.f('ix_notes_created_at'), table_name='notes')
    op.create_index('idx_notes_domain', 'notes', ['domain'], unique=False)
    op.create_index('idx_notes_created_at', 'notes', ['created_at'], unique=False)
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'lead_scores',
        'Calculated readiness scores and segments for domains',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_lead_scores_updated_at'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_segment'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_readiness_score'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_domain'), table_name='lead_scores')
    op.create_index('idx_lead_scores_updated_at', 'lead_scores', ['updated_at'], unique=False)
    op.create_index('idx_lead_scores_segment', 'lead_scores', ['segment'], unique=False)
    op.create_index('idx_lead_scores_readiness_score', 'lead_scores', ['readiness_score'], unique=False)
    op.create_index('idx_lead_scores_domain', 'lead_scores', ['domain'], unique=False)
    op.alter_column('lead_scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('favorites', sa.Column('user_id_new', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'favorites',
        'User favorites for domains, session-based (G17: CRM-lite)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_domain'), table_name='favorites')
    op.create_index('idx_favorites_user_id_new', 'favorites', ['user_id_new'], unique=False)
    op.create_index('idx_favorites_user_id', 'favorites', ['user_id'], unique=False)
    op.create_index('idx_favorites_domain_user_id', 'favorites', ['domain', 'user_id'], unique=False)
    op.create_index('idx_favorites_domain', 'favorites', ['domain'], unique=False)
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'domain_signals',
        'DNS and WHOIS analysis results for domains',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_domain_signals_scanned_at'), table_name='domain_signals')
    op.drop_index(op.f('ix_domain_signals_scan_status'), table_name='domain_signals')
    op.drop_index(op.f('ix_domain_signals_mx_root'), table_name='domain_signals')
    op.drop_index(op.f('ix_domain_signals_local_provider'), table_name='domain_signals')
    op.drop_index(op.f('ix_domain_signals_id'), table_name='domain_signals')
    op.drop_index(op.f('ix_domain_signals_domain'), table_name='domain_signals')
    op.drop_index(op.f('ix_domain_signals_dmarc_coverage'), table_name='domain_signals')
    op.create_index('idx_domain_signals_scanned_at', 'domain_signals', ['scanned_at'], unique=False)
    op.create_index('idx_domain_signals_scan_status', 'domain_signals', ['scan_status'], unique=False)
    op.create_index('idx_domain_signals_mx_root', 'domain_signals', ['mx_root'], unique=False)
    op.create_index('idx_domain_signals_local_provider', 'domain_signals', ['local_provider'], unique=False)
    op.create_index('idx_domain_signals_domain', 'domain_signals', ['domain'], unique=False)
    op.create_index('idx_domain_signals_dmarc_coverage', 'domain_signals', ['dmarc_coverage'], unique=False)
    op.alter_column('domain_signals', 'scanned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('domain_signals', 'scan_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_table_comment(
        'companies',
        'Normalized company information with unique domain constraint',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_companies_updated_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_tenant_size'), table_name='companies')
    op.drop_index(op.f('ix_companies_provider'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_contact_quality_score'), table_name='companies')
    op.create_index('idx_companies_updated_at', 'companies', ['updated_at'], unique=False)
    op.create_index('idx_companies_tenant_size', 'companies', ['tenant_size'], unique=False)
    op.create_index('idx_companies_provider', 'companies', ['provider'], unique=False)
    op.create_index('idx_companies_domain', 'companies', ['domain'], unique=False)
    op.create_unique_constraint('companies_domain_key', 'companies', ['domain'])
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'alerts',
        'Generated alerts for domain changes (G18)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_domain'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.create_index('idx_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('idx_alerts_domain', 'alerts', ['domain'], unique=False)
    op.create_index('idx_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('idx_alerts_alert_type', 'alerts', ['alert_type'], unique=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_table_comment(
        'alert_config',
        'Alert configuration preferences (G18)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_alert_config_user_id'), table_name='alert_config')
    op.drop_index(op.f('ix_alert_config_id'), table_name='alert_config')
    op.drop_index(op.f('ix_alert_config_enabled'), table_name='alert_config')
    op.drop_index(op.f('ix_alert_config_alert_type'), table_name='alert_config')
    op.create_index('idx_alert_config_user_id', 'alert_config', ['user_id'], unique=False)
    op.create_index('idx_alert_config_enabled', 'alert_config', ['enabled'], unique=False)
    op.create_index('idx_alert_config_alert_type', 'alert_config', ['alert_type'], unique=False)
    op.create_unique_constraint('alert_config_user_id_alert_type_notification_method_key', 'alert_config', ['user_id', 'alert_type', 'notification_method'])
    op.alter_column('alert_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('alert_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('alert_config', 'frequency',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'immediate'::character varying"))
    op.alter_column('alert_config', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('alert_config', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'default'::character varying"))
    # ### end Alembic commands ###
